name = "journey"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[assets]
binding = "ASSETS"
directory = "./web/dist"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "development"
